export const MOCK_CREDENTIALS = {
  email: 'professor@academic.edu',
  password: 'correct2024',
};

export const MOCK_CORRECTIONS_PAGE_1 = [
  {
    id: 1,
    error: 'Incorrect verb tense in the introductory paragraph.',
    original_text: 'the experiment demonstrates',
    suggestion: 'the experiment demonstrated',
    severity: 'moderate',
  },
  {
    id: 2,
    error: 'Missing definite article before the noun phrase.',
    original_text: 'According to literature',
    suggestion: 'According to the literature',
    severity: 'minor',
  },
  {
    id: 3,
    error: 'Subject-verb disagreement in the main clause.',
    original_text: 'The data indicates that',
    suggestion: 'The data indicate that',
    severity: 'major',
  },
];

export const MOCK_CORRECTIONS_PAGE_2 = [
  {
    id: 4,
    error: 'Ambiguous pronoun reference obscuring the antecedent.',
    original_text: 'this leads to',
    suggestion: 'this discrepancy leads to',
    severity: 'moderate',
  },
  {
    id: 5,
    error: 'Run-on sentence requiring conjunction insertion.',
    original_text: 'the results were inconclusive the hypothesis',
    suggestion: 'the results were inconclusive; therefore, the hypothesis',
    severity: 'major',
  },
];

export const MOCK_CORRECTIONS = {
  1: MOCK_CORRECTIONS_PAGE_1,
  2: MOCK_CORRECTIONS_PAGE_2,
};

export const MOCK_EVALUATION_TEMPLATE = (acceptedErrors) => {
  const errorCount = acceptedErrors.length;
  const categories = acceptedErrors.reduce((acc, err) => {
    acc[err.severity] = (acc[err.severity] || 0) + 1;
    return acc;
  }, {});

  return `
EVALUATIVE SUMMARY OF ACADEMIC CORRECTION ANALYSIS
===================================================

Student Report Assessment — Generated by AI Correction Assistant

Overview:
The document review process identified ${errorCount} linguistic and structural
irregularities requiring pedagogical intervention. The following analysis
categorizes the accepted corrections by severity and provides
recommendations for academic writing improvement.

Severity Distribution:
${Object.entries(categories)
  .map(
    ([severity, count]) =>
      `  - ${severity.charAt(0).toUpperCase() + severity.slice(1)}: ${count} occurrence(s)`
  )
  .join('\n')}

Areas Requiring Reinforcement:
${acceptedErrors
  .map((err) => `  * ${err.error} (Severity: ${err.severity})`)
  .join('\n')}

Pedagogical Recommendations:
1. The student should engage in targeted grammar exercises focusing on
   the identified error categories above.
2. A comprehensive review of academic writing conventions is advised,
   with particular emphasis on subject-verb agreement and article usage.
3. It is recommended that the student utilize proofreading checklists
   prior to final submission to minimize recurrent errors.

Conclusion:
The student demonstrates foundational competency in academic writing but
requires structured intervention to address persistent grammatical and
stylistic deficiencies. Continued guided practice is strongly encouraged.
`.trim();
};
